### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by DilanRona** [timvisee/merge-mania#19]
`
> merge-mania-client@0.1.0 build
> vue-cli-service build

 ERROR  Error: Compiling RuleSet failed: Evaluation of condition function threw error (at clonedRuleSet-40.exclude[0]: filepath => {
                    // always transpile js in vue files
                    if (/\.vue\.jsx?$/.test(filepath)) {
                      return false
                    }
                    // exclude dynamic entries from cli-service
                    if (filepath.startsWith(cliServicePath)) {
                      return true
                    }
                    // check if this is something the user explicitly wants to transpile
                    if (options.transpileDependencies.some(dep => {
                      if (typeof dep === 'string') {
                        return filepath.includes(path.normalize(dep))
                      } else {
                        return filepath.match(dep)
                      }
                    })) {
                      return false
                    }
                    // Don't transpile node_modules
                    return /node_modules/.test(filepath)
                  })
Error: Compiling RuleSet failed: Evaluation of condition function threw error (at clonedRuleSet-40.exclude[0]: filepath => {
            // always transpile js in vue files
            if (/\.vue\.jsx?$/.test(filepath)) {
              return false
            }
            // exclude dynamic entries from cli-service
            if (filepath.startsWith(cliServicePath)) {
              return true
            }
            // check if this is something the user explicitly wants to transpile
            if (options.transpileDependencies.some(dep => {
              if (typeof dep === 'string') {
                return filepath.includes(path.normalize(dep))
              } else {
                return filepath.match(dep)
              }
            })) {
              return false
            }
            // Don't transpile node_modules
            return /node_modules/.test(filepath)
          })
    at RuleSetCompiler.error (/home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:373:10)
    at RuleSetCompiler.compileCondition (/home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:238:16)
    at /home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:253:10
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileCondition (/home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:252:28)
    at /home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/BasicMatcherRulePlugin.js:29:40
    at Hook.eval [as call] (eval at create (/home/rupert/merge-mania/client/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
    at RuleSetCompiler.compileRule (/home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:177:19)
    at cloneRule (/home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin-webpack5.js:221:40)
    at /home/rupert/merge-mania/client/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin-webpack5.js:119:9
`

**Comment by timvisee** [comment]
It has been a while since I've built this.

What command are you using, and what node/npm version are you using?
